/* Xresources preferences to load at startup */
ResourcePref resources[] = {
	//{ "systraypinning",             INTEGER,   &systraypinning                  },
	//{ "systrayspacing",             INTEGER,   &systrayspacing                  },
	//{ "systraypinningfailfirst",    INTEGER,   &systraypinningfailfirst         },
	//{ "showsystray",                INTEGER,   &showsystray                     },
	//{ "statussep",                  STRING,    &statussep                       },
	{ "extrabarmon",                INTEGER,   &extrabarmon                     },
	{ "borderpx",                   INTEGER,   &borderpx                        },
	{ "snap",                       INTEGER,   &snap                            },
	{ "showbar",                    INTEGER,   &showbar                         },
	{ "topbar",                     INTEGER,   &topbar                          },
	{ "dmenufont",                  STRING,    &dmenufont                       },
	{ "normbgcolor",                STRING,    &normbgcolor                     },
	{ "normfgcolor",                STRING,    &normfgcolor                     },
	{ "selbgcolor",                 STRING,    &selbgcolor                      },
	{ "selfgcolor",                 STRING,    &selfgcolor                      },
	{ "normbordercolor",            STRING,    &normbordercolor                 },
	{ "selbordercolor",             STRING,    &selbordercolor                  },
	{ "mfact",                      FLOAT,     &mfact                           },
	{ "nmaster",                    INTEGER,   &nmaster                         },
	{ "resizehints",                INTEGER,   &resizehints                     },
	{ "termcol0",                   STRING,    &termcol0                        },
	{ "termcol1",                   STRING,    &termcol1                        },
	{ "termcol2",                   STRING,    &termcol2                        },
	{ "termcol3",                   STRING,    &termcol3                        },
	{ "termcol4",                   STRING,    &termcol4                        },
	{ "termcol5",                   STRING,    &termcol5                        },
	{ "termcol6",                   STRING,    &termcol6                        },
	{ "termcol7",                   STRING,    &termcol7                        },
	{ "termcol8",                   STRING,    &termcol8                        },
	{ "termcol9",                   STRING,    &termcol9                        },
	{ "termcol10",                  STRING,    &termcol10                       },
	{ "termcol11",                  STRING,    &termcol11                       },
	{ "termcol12",                  STRING,    &termcol12                       },
	{ "termcol13",                  STRING,    &termcol13                       },
	{ "termcol14",                  STRING,    &termcol14                       },
	{ "termcol15",                  STRING,    &termcol15                       },
};

